### ISSUE TITLE
ActionSheet不能设置再显示呀

### ISSUE THREAD

**Issue by runhwguo** [Janmin/weui-vue#1]
isShow没有接口设置为true呀

**Comment by jamin-xie** [comment]
![image](https://user-images.githubusercontent.com/16360530/38074744-5c425fbe-3362-11e8-8769-0e1f3aad8c75.png)

**Comment by runhwguo** [comment]
嗯嗯，我当时操作了actionsheetShow，只有第一次生效，后来再改变这个变量值，不会显示actionsheet

**Comment by jamin-xie** [comment]
那可能是bug，我检查一下

**Comment by jamin-xie** [comment]
现在已经修复了:show改为v-model即可，npm也将同步更新

**Comment by runhwguo** [comment]
棒棒棒

**Comment by runhwguo** [comment]
actionsheet在mounted时，不应该设置值，不然第一次设置值永远是true！
你代码里如下：
    mounted() {
      if (this.value) {
        this.isShow = true
      }
    },

**Comment by jamin-xie** [comment]
是我的疏忽，没有仔细审查，感谢~！

**Comment by runhwguo** [comment]
嗯嗯，close issue
